project:
  title: "intro-git-github"
  render:
    - "*.qmd"
    - "!LICENCE.md"
embed-resources: true
format:
  revealjs:
    footer: "<https://postcard.nhsrcommunity.com/>"
    code-link: true
    preview-links: true
    logo: https://raw.githubusercontent.com/nhs-r-community/assets/main/logo/nhsr-logo.svg
author: "Zoë Turner"
execute: 
  echo: true
  eval: false
title-slide-attributes: 
  data-background-color: "#43464B"
brand: _brand.yml

#  output-dir: "/slides"
