---
title: "Introduction to Git and GitHub"
title-slide-attributes: 
  data-background-color: "#43464B"
subtitle: "Session - Commit to main (and undo last commit!)"
author: "Zoë Turner"
format:
  revealjs:
    theme: [default, nhsr-quarto.scss]
    logo: https://raw.githubusercontent.com/nhs-r-community/assets/main/logo/nhsr-logo.svg
    code-link: true
    css: nhsr-quarto.scss
    preview-links: true
execute: 
  echo: true
  eval: false
embed-resources: true  
---

## Not recommended, but sometimes useful

The `pr_*` functions all relate to Pull Requests but it is possible to commit to main directly

Commit work using

```{r}
gert::git_commit_all("This is a message")

# or

gert::git_add("file.qmd")
gert::git_commit("This is a message")

```

and then use the `Push` button in the Git RStudio pane 

## Accidental commits!

If you commit by accident to any branch, but particularly `main`, you can undo the last commit

In fact, you can undo any number of last commits!

This has to be done in the `Terminal` though ($)!

```{bash}
git reset --soft HEAD~1
```

:::{.callout-warning collapse=false appearance='default' icon=true}
## Resetting doesn't delete
Be careful if you are trying to undo something sensitive, a reset is not a deletion
:::

## Moving changes from one branch to another

What if you've made a few changes that you want to keep but committed to `main`?

- In RStudio create a new branch (which will have all the changes)
- Return to `main`
- Use the `terminal` to reset the commits you don't want

## End session
